### ISSUE TITLE
[ENH] Add C# function pointers support for ILua.PushCFunction

### ISSUE THREAD

**Issue by GlebChili** [GmodNET/GmodDotNet#46]
# Description

We should make use of C# 9.0 [function pointers](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-9.0/function-pointers.md) and [UnmanagedCallersOnly attribute](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.unmanagedcallersonlyattribute?view=net-5.0) for better performance and code maintenance.

# TODO

- [ ] Add `PushCFunction(delegate* unmanaged[Cdecl]<IntPtr, int>)` method definition to `ILua` interface.

- [ ] Add method implementation to to `Lua` class.

- [ ] Add corresponding test.
